apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../manifest/argo/namespaces
  - ../../manifest/argo/container-security
  - ../../manifest/argo/developer-argo
  - ../../manifest/argo/infra-argo