apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../manifest/argo/namespaces
  - ../../manifest/argo/container-security
  - ../../manifest/argo/developer-argo
  - ../../manifest/argo/openshift-pipelines


patches:
  - target:
      group: argoproj.io
      version: v1alpha1
    path: patch-app-version.yaml
  