apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-security
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
    path: manifest/charts/container-security
    repoURL: 'https://github.com/jland-redhat/cluster-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}