kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
    g, argo-admins, role:admin
  policy.default: 'role:readonly'
  scopes: '[groups]'
