apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: developer-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

  labels:
    owner: {{ .Values.owner }}
  name: {{ .Values.name }}
spec: {}
