apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-app
spec:
  source:
    helm:
      values: |
          clusterName: example-cluster-1
          namespaces:
            - example-namespace-1
            - example-namespace-2